version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/deployment/migration-assistant-solution"
    schedule:
      interval: "weekly"
    groups:
      migration-assistant-npm:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/deployment/cdk/opensearch-service-migration"
    schedule:
      interval: "weekly"
    groups:
      opensearch-cdk-npm:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/" # Adjust if build.gradle is in a subdirectory
    schedule:
      interval: "weekly"
    groups:
      gradle-all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.opensearch:*"
      - dependency-name: "org.apache.lucene:*"

  - package-ecosystem: "github-actions"
    directory: "/" # GitHub Actions workflows live in .github/workflows
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"
