# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - DocumentsFromSnapshotMigration/docker/Dockerfile
      - DocumentsFromSnapshotMigration/docker/TestSource_ES_5_6/Dockerfile
      - DocumentsFromSnapshotMigration/docker/TestSource_ES_6_8/Dockerfile
      - DocumentsFromSnapshotMigration/docker/TestSource_ES_7_10/Dockerfile
      - DocumentsFromSnapshotMigration/docker/TestSource_ES_7_17/Dockerfile
      - DocumentsFromSnapshotMigration/docker/TrafficGenerator/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/captureProxyBase/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/grafana/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/k8sConfigMapUtilScripts/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile
      - TrafficCapture/dockerSolution/src/main/docker/otelCollector/Dockerfile
      - TrafficCapture/trafficCaptureProxyServerTest/src/main/docker/nginx/Dockerfile
      - dev-tools/jenkinsdocker/Dockerfile
    schedule:
      interval: "daily"
