version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Adjust if package.json is in a subdirectory
    schedule:
      interval: "weekly"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/" # Adjust if requirements.txt is in a subdirectory
    schedule:
      interval: "weekly"
    groups:
      python-all:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/" # Adjust if build.gradle is in a subdirectory
    schedule:
      interval: "weekly"
    groups:
      gradle-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/" # GitHub Actions workflows live in .github/workflows
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"
